const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
const EDIT_RECORD = 'EDIT_RECORD';
const SET_EDIT_RECORD = 'SET_EDIT_RECORD';
const DELETE_RECORD = 'DELETE_RECORD';
const SET_DELETE_RECORD = 'SET_DELETE_RECORD';
const ADD_RECORD = 'ADD_RECORD';
const SET_ADD_RECORD = 'SET_ADD_RECORD';
const SORT_BY_DATE='SORT_BY_DATE';
const SEARCH_RECORD = 'SEARCH_RECORD';
const FILTER_BY_BRANCH = 'FILTER_BY_BRANCH';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
const FILTER_BY_STATUS = 'FILTER_BY_STATUS';
const SET_API_ERROR = 'SET_API_ERROR';
const FILTERED_DATA = 'FILTERED_DATA';
const FILTER_BY_FROMDATE = 'FILTER_BY_FROMDATE';
const FILTER_BY_TODATE = 'FILTER_BY_TODATE';
const SET_ID = 'SET_ID';

export {
    GET_INITIAL_DATA,
    EDIT_RECORD,
    DELETE_RECORD,
    ADD_RECORD,
    SORT_BY_DATE,
    SET_INITIAL_DATA,
    SET_EDIT_RECORD,
    SET_DELETE_RECORD,
    SET_ADD_RECORD,
    SEARCH_RECORD,
    FILTER_BY_BRANCH,
    FILTER_BY_TYPE,
    FILTER_BY_STATUS,
    SET_API_ERROR,
    FILTERED_DATA,
    FILTER_BY_FROMDATE,
    FILTER_BY_TODATE,
    SET_ID
}